# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Benjamin Lee
title: Data Scientist
email: lilphd99@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: 
github_username:  sweetscientist
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: 
linkedin_username: benjamin-s-lee
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: 
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
google_analytics: "UA-191793676-1"

# About Section
# about_title: About Me
about_profile_image: # add image here
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Ben and I'm a data scientist. I enjoy buiding tools and managing process efficiency for analytical projects. 
  
  I am skilled in: Python, R, SQL, a bit of C++ / Java

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Genetic algorithm 
        link: in the works
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Survival of the Fittest
        description: | # this will include new lines to allow paragraphs
          This is about **Genetic Algorithhms(GA)**, which is an algorithm based on Darwin's evolution theory.
          I started this project as a way of learning GA and it has since grown into a ubiquotous tool.
   
      - layout: top-middle
        
        title: Quantitative Finance
        link: LINK (https://github.com/sweetscientist/quantitative_finance)
        #link_text: https://github.com/sweetscientist/quantitative_finance
        additional_links:
          - title:  sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          “Data really powers everything that we do.” – Jeff Weiner
        description: | # this will include new lines to allow paragraphs
          This is a series of notebooks that I am developing while I was explore ways to improve my trading system.
          It will have data collection, strategy development, portfolio optimization along with technical analysis tools. 
     
          
     
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: BMO Financial Group
        link: https://www.bmoharris.com
        # link_text: bmoharris.com
        sub_title: Data Scientist
        caption: May 2020 - Present
        quote: >
          Contact optimization by understanding human financial behaviors and building predictive models
        description: | # this will include new lines to allow paragraphs
          Every company needs proper marketing that understands consumer behavior. 
          While building databases is a critical fundamental step my team also looks for patterns between campaigns and customer behavior.  
          Simply building queries and predictive models is not enough to do this, so we work with our partners and branch personnel to optimize our decision at all levels.
      
      - layout: left
        title: Constellation Brands
        link: https://www.cbrands.com/
        # link_text: cbrands.com
        sub_title: Sr Analyst
        caption: May 2018 - May 2020
        quote: >
          Maximize revenue by researching economic trends, social sciences, and flavor for beer, wine, and spirits
        description: | # this will include new lines to allow paragraphs
          We all like to enjoy a cold beer and kick back. In my case, I enjoyed brewing beer at home and wondering what I pay for.
          This got me interested in how the world of finance impacts the alcohol industry.
          Data collections tools, time series models, and decision making frameworks were built that improved sales significantly.
          
      - layout: left
        title: AB Inbev
        link: https://www.ab-inbev.com
        # link_text: ab-inbev.com
        sub_title: Data Science Intern
        caption: Dec 2016 - April 2018
        quote: >
          Jack of all trades at the Bud Lab, AB Inbev's analytics research lab
        description: | # this will include new lines to allow paragraphs
          We all like to enjoy a cold beer and kick back. In my case, I enjoyed brewing beer at home and wondering what I pay for.
          This got me interested in how the world of finance impacts the alcohol industry.
          Data collections tools, time series models, and decision making frameworks were built that improved sales significantly.
          
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Illinois @ Urbana-Champaign
        caption: 2010 - 2016
        sub_title: BSc Statistics
        quote: >
          During my time in Champaings, I learned how to constantly learn regardless of what I am doing. 
        description: | # this will include new lines to allow paragraphs
          During my time as a college student, I spent **2 years** in the Korea military, which helped me understand what I want to do in the future and build a plan.
          Started as an Industrial Engineering major and then transferred to Statistics after taking a Probability for Engineers class taught by Professor Richard Sowers. 
          This experience has allowed me to enjoy what and I do and constantly push myself further. 
          
          
          
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I can speak in: English & Korean as a native, Japanese enough to travel, and a bit of Chinese

      Alongside my interests in understanding the world through data and programming some of my other interests and hobbies are:
      - Cooking & Baking
      - Boxing
      - Gaming
      
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
